// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/generate': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/generate').default>>>>
    }
    '/api/admin/revoke': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/revoke').default>>>>
    }
    '/api/admin/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats').default>>>>
    }
    '/api/blacklist/:action': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blacklist/[action]').default>>>>
    }
    '/api/blacklist/add': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blacklist/add').default>>>>
    }
    '/api/blacklist/check': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blacklist/check').default>>>>
    }
    '/api/codes/generate': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/codes/generate').default>>>>
    }
    '/api/codes/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/codes/list').default>>>>
    }
    '/api/codes/validate-simple': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/codes/validate-simple').default>>>>
    }
    '/api/codes/validate-url': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/codes/validate-url').default>>>>
    }
    '/api/codes/validate': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/codes/validate').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}