// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/8 13:47:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/ql/Desktop/activation-code-system/activation-code-system/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/plugins/**/*.{js,ts,mjs}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/composables/**/*.{js,ts,mjs}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/utils/**/*.{js,ts,mjs}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ql/Desktop/activation-code-system/activation-code-system/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;